export const UMAMI_WEBSIT_ID = process.env.UMAMI_WEBSIT_ID;

export const UMAMI_API_CLIENT_USER_ID = process.env.UMAMI_API_CLIENT_USER_ID;

export const UMAMI_API_CLIENT_SECRET = process.env.UMAMI_API_CLIENT_SECRET;

export const UMAMI_API_CLIENT_ENDPOINT = process.env.UMAMI_API_CLIENT_ENDPOINT;
